README.md, pom.xml
Fix #112 
Update the Pulsar version from `2.6.0-SNAPSHOT` to `2.6.0`.
Modify the file `README.md`.
=> Update pulsar version from `2.6.0-SNAPSHOT` to `2.6.0`.

pom.xml
Update pulsar version to 2.6.2.0
=> Update pulsar version to 2.6.2.0

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java, pom.xml
Fixes #144 
Bump pulsar version to `2.7.0.1`.
=> Bump pulsar version to 2.7.0.1

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java, pom.xml
Pulsar weekly release version `2.7.0.2-rc-202012311246`
Bump pulsar version from 2.7.0.1 to 2.7.0.2-rc-202012311246
=> Bump pulsar version from 2.7.0.1 to 2.7.0.2-rc-202012311246

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
=> bump to 2.7.0.3

scripts/set-pulsar-version.sh
**Motivation**
Add script for updating pulsar version.
=> Add scripts for updating pulsar

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
=> Bump pulsar to 2.7.0.4-rc-202101150854

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
=> Bump pulsar to 2.7.0.4

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
=> Bump 2.7.0.7 rc 202102041604

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
=> Bump pulsar to 2.7.0.7

README.md
Add Maintainer from community in readme
=> [Doc] Add Maintainer from community

README.md
[doc]Add Ran & Penghui as Maintainer
=> [doc]Add Ran & Penghui as Maintainer

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
weekly release verify 2.7.1.1-rc-202103251930
=> weekly release verify 2.7.1.1-rc-202103251930

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
=> bump pulsar to `2.7.1.1`

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
=> Bump pulsar to 2.7.1.3-rc-202104091034

amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
=> Revert "Bump pulsar version to 2.7.2.3"

.github/workflows/pr-qpid-jms-test.yml, .github/workflows/pr-test.yml
=> [CI] Fix ci workflow on event

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java, pom.xml
Fix get applied advertised address.
=> [Branch-2.7.2] Fix get applied advertised address

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java, pom.xml
1. bump Pulsar version to `2.8.0.6`.
2. fix the consumer construct method.
=> Fix the consumer construct method

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java
Fixes #<xyz>
*(or)*
*(or)*
*(example:)*
*If …
=> Fix the failed tests

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/MessagePublishContext.java
[Issues#214]bug fix Release ByteBuf after sending.
https://github.com/streamnative/aop/issues/214
=> [Issues#214]bug fix: Release ByteBuf after sending.

pom.xml
Bump log4j2 version to `2.17.0`
=> Bump log4j2 version to `2.17.0`

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java, pom.xml
Fix test for Pulsar `2.10.0.0-rc3` change
=> Fix test for Pulsar `2.10.0.0-rc3` change

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockDispatcher.java, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java, pom.xml
Adjust logic for Pulsar `2.10.0.0-rc4`
=> Adjust logic for Pulsar `2.10.0.0-rc4`

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java, pom.xml
=> Bump Pulsar to `2.10.0.0-rc9`

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java, pom.xml
=> [Branch-2.8.2] Bump Pulsar to `2.8.2.11`

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java, pom.xml
=> Bump pulsar to `2.9.2.6`

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java, pom.xml
=> Bump Pulsar to `2.9.2.11`

pom.xml
Bump Jackson version to `2.13.2`
=> Bump Jackson version to `2.13.2`

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java, pom.xml
=> Bump Pulsar `2.10.0.0`

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java, pom.xml
Bump Pulsar to `2.10.0.5` for branch-2.10.0
=> Bump Pulsar to `2.10.0.5` for branch-2.10.0

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpEntryWriter.java
The PR #530 introduce a memory leak problem.
After adding entries release the data.
=> [fix] After adding entries release the data

pom.xml
Bump Pulsar to `2.10.1.5` for branch `2.10.1`.
=> Bump pulsar 2.10.1.5 for branch 2.10.1

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannelInitializer.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpServiceConfiguration.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyConfiguration.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyHandler.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ServiceChannelInitializer.java
Consolidation flush optimization for the netty channel.
Add consolidation flush handler at the netty channel pipeline.
=> Consolidation flush optimization for the netty channel

.github/workflows/pr-qpid-jms-test.yml, .github/workflows/pr-test.yml, .github/workflows/release-note.yml, .github/workflows/release.yml, amqp-impl/pom.xml, pom.xml, tests-qpid-jms-client/pom.xml, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests/pom.xml
=> Revert "Bump aop version to 2.10.1.8"

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpMessageRouter.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
Adjust permits for AMQP consumers.
*(or)*
*(or)*
*(example:)*
- The rest endpoints: (yes / no)
- The admin cli options: (yes …
=> Adjust permits for AMQP consumer

amqp-client-auth/pom.xml, amqp-impl/pom.xml, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConnection.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/MessageFetchContext.java, pom.xml, tests-qpid-jms-client/pom.xml, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests/pom.xml, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
Bump Project to `3.0.0.1-SNAPSHOT`.
Bump Pulsar to `3.0.0.1-SNAPSHOT`.
Fix compatibility problems.
=> Bump Project to 3.0.0.1-SNAPSHOT

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeServiceImpl.java
Fix NPE.
Check the box below and label this PR (if you have committer privilege).
Need to update docs?
=> Fix - NPE may throw when declare exchange.

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpServiceConfiguration.java
Doc description error.
Check the box below and label this PR (if you have committer privilege).
Need to update docs?
=> Fix - Doc description error.

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
Remove useless test code about the compactor.
=> [test] Remove useless test code about compactor

amqp-client-auth/pom.xml, amqp-impl/pom.xml, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java, pom.xml, tests-qpid-jms-client/pom.xml, tests/pom.xml
1. Bump Pulsar version to `3.3.0-SNAPSHOT`.
2. Bump project version to `3.3.0-SNAPSHOT`.
=> Bump version 3.3.0-SNAPSHOT

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpPulsarConsumer.java, pom.xml
=> [branch-3.0] Bump Pulsar 3.0.4.5

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpPulsarConsumer.java, pom.xml
=> Bump Pulsar 3.2.2.6

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpEntryWriter.java, pom.xml
=> Bump Pulsar 3.2.2.7

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpEntryWriter.java, pom.xml
=> Bump Pulsar 3.0.4.6

.github/workflows/pr-test.yml, amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java, pom.xml, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
=> [branch-3.0] Bump Pulsar 3.0.5.5

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
=> Bump Pulsar 3.4.0-SNAPSHOT

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeMessageRouter.java
Change read max position to earliest position to avoid potential NPE.
=> [fix] Change read max position to earliest position

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeMessageRouter.java
Cherry-pick https://github.com/streamnative/aop/pull/1325.
=> [branch-3.3][fix] Change read max position to earliest position

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeMessageRouter.java, pom.xml
Cherry-pick https://github.com/streamnative/aop/pull/1325.
=> [branch-3.0][fix] Change read max position to earliest position

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/authentication/AuthenticationProviderBasic.java, pom.xml
Improve authentication metrics for Pulsar `4.0.0-SNAPSHOT`.
Improve authentication metrics.
=> Improve authentication metrics for Pulsar 4.0.0-SNAPSHOT

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpEntryWriter.java, amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java
Fix the publish latency unit.
Remove useless logs.
=> [fix] Fix the publish latency unit

tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/qpid/core/AoPBrokerAdmin.java, tests/src/test/java/com/rabbitmq/client/test/BrokerTestCase.java, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTokenAuthenticationTestBase.java
Remove useless check in tests.
=> [test] Remove useless check in tests

pom.xml, scripts/build.sh
* Fix sn bom version typo
* Fix build script path
=> Fix build script

amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java, pom.xml, tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java, tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
=> Bump pulsar 3.3.3.4

pom.xml
Add back qpid-test-utils package from sn-bom because it is test scope
=> Add back qpid-test-utils package

amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyConnection.java, pom.xml, scripts/build.sh
Revert to using the nar package.
Add qpid dependencies for the module `amqp-impl`.
=> Add qpid dependencies
