- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyConfiguration.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyService.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpConfigNameTest.java
Currently, the AoP proxy use `advertisedAddress` in config file `broker.conf` directly, this is not unreasonable.
Make the AoP `ProxyConfiguration` independent of `AmqpServiceConfiguration`, add the config `brokerServiceURL` used to connect with Pulsar Broker.
This change is already covered by existing tests.
- The default values of configurations: (yes)
- Anything that affects deployment: (yes)
- Does this pull request introduce a new feature? (no)
> Improve AoP ProxyConfiguration

- amqp-impl/pom.xml
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java
- pom.xml
- tests-qpid-jms-client/pom.xml
- tests/pom.xml
Besides bumping pulsar version, this PR also fixes the compile error caused by new `Subscription` interface.
> Bump pulsar to 2.7.0.8-rc-202102191415

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
- pom.xml
https://github.com/apache/pulsar/pull/10961 changed the method signature of `ServiceConfigurationUtils#getAppliedAdvertisedAddress`, which causes AoP build failure.
Upgrade the Pulsar dependency to 2.8.0.4 that contains https://github.com/apache/pulsar/pull/10961, then add the second parameter to `getAppliedAdvertisedAddress`.
It should be noted that since Pulsar 2.8.0.4 introduced the API incompatibility with 2.8.0, after this change, AoP >= 2.8.0.4 cannot be compatible with Pulsar < 2.8.0.4 including the stable version 2.8.0.
> Apply new getAppliedAdvertisedAddress signature

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
- pom.xml
1. bump Pulsar version to `2.7.2.8`.
2. fix consumer construct method.
> [Branch-2.7.2] Fix the consumer construct method

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyService.java
Currently, the subscribe operation is a block operation in an asynchronous method, this may block the thread.
Make the subscribe operation asynchornously.
This change is already covered by existing tests.
> Make the subscribe operation asynchronously

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/utils/MessageConvertUtils.java
Reason: MessageConvertUtils.entryToIndexMessage and MessageConvertUtils.entryToAmqpBody called ByteBuf.retain(),
but did not call release.
> Solve the problem of insufficient off-heap memory allocation during consumption.

- pom.xml
We need to upgrade the log4j2 version in projects due to security problems in log4j. refer to https://nvd.nist.gov/vuln/detail/CVE-2021-44228#toggleConfig1
Bump log4j2 version to `2.16.0`.
> Bump log4j2 version to `2.16.0`

- pom.xml
Bump log4j2 version to `2.17.1` to address CVE-2021-44832.
> Bump log4j2 version to `2.17.1`

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpTopicManager.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeContainer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueContainer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/common/exception/EmptyLookupResultException.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/common/exception/NamespaceNotFoundException.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/common/exception/package-info.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyService.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java
- pom.xml
- tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
Bump Pulsar to `2.10.0.0-rc-1` and adjust some logic.
A key point change is that, if the namespace isn't existing, the topic manager will return a fenced topic, I add a check for the fenced topic.
Add a namespace existing check before getting the topic.
> Bump Pulsar to `2.10.0.0-rc-1`

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpPullConsumer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpTopicManager.java
- pom.xml
1. Bump Pulsar to `2.10.0.0-rc2`.
2. Adjust AMQP consumer constructor for Pulsar `2.10.0.0-rc2` change.
Don't change the AoP behavior, the maxUnackedMessages is still 0.
This change is already covered by existing tests.
> Adjust AMQP consumer constructor

- pom.xml
Currently, the pulsar-broker has a conflict dependency problem https://github.com/apache/pulsar/issues/15290. This will cause failure when building the project. And we need to resolve the dependency problem in Pulsar, after Pulsar fixes the problem, we could improve this change.
```
Cannot resolve Could not resolve version conflict among
io.grpc:grpc-core:jar:1.18.0
io.streamnative:pulsar-zookeeper-utils:jar:2.9.2.14 -> org.apache.bookkeeper:stream-storage-server:jar:4.14.4 -> org.apache.bookkeeper:stream-storage-java-client:jar:4.14.4 -> io.grpc:grpc-core:jar:1.42.1
io.streamnative:pulsar-zookeeper-utils:jar:2.9.2.14 -> org.apache.bookkeeper:stream-storage-server:jar:4.14.4 -> org.apache.bookkeeper:stream-storage-java-client:jar:4.14.4 -> io.grpc:grpc-testing:jar:1.42.1 -> …
```
> Exclude grpc-related packages from pulsar-broker

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpChannelMethodTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
Fixes #470
pulsar-protocol-handler-amqp: 2.8.1.9
Client pom.xml use：com.alibaba.mq-amqp#mq-amqp-client#1.0.5
Client config：
```
spring.amqp.order.host = 
spring.amqp.order.port = 
spring.amqp.order.virtual-host = 
spring.amqp.template.order.mandatory = true
spring.amqp.order.publisher-confirms = true
spring.amqp.order.publisher-returns = true
#spring.amqp.listener.direct.acknowledge-mode = manual
spring.amqp.listener.simple.order.acknowledge-mode = manual
spring.amqp.listener.simple.order.concurrency = 2
spring.amqp.listener.simple.order.max-concurrency = 2
spring.amqp.listener.simple.order.prefetch = 200
spring.amqp.listener.order.auto-startup = true
```
spring bean config:
```
@Slf4j
@Component
public class AMQPConfig {
private static final String ACKNOWLEDGE_AUTO = "auto";
private …
```
> [Issues#470]bug fix: Message delivery lost.

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpServiceConfiguration.java
Fixes Issue: #527 
In version 2.9.*, if amqpListeners cannot be configured dynamically, Aop Proxy will not be available. When YAML is deployed in K8S, StatefulSet shares the ConfigMap configuration. Each Pod configuration is the same and cannot be configured dynamically. The production client generates the following error:
```
java.net.SocketTimeoutException: Timeout during Connection negotiation
at com.rabbitmq.client.impl.AMQConnection.handleSocketTimeout(AMQConnection.java:815)
at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:727)
at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:646)
at java.lang.Thread.run(Thread.java:748)
java.io.IOException
at …
```
> bugfix: amqpListeners cannot be configured dynamically.

- scripts/build.sh
- scripts/get-version.sh
In order to facilitate the management of the release process, we need to strictly standardize the naming of scripts and the structure of related directories 
We changed the structure of related scripts and directories.
Not needed
> Refactor the structure of release scripts to facilitate CI management

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpBrokerDecoder.java
Master Issue: #589
After each client is connected to the broker, 4MB of memory is allocated for each connection in `io/streamnative/pulsar/handlers/amqp/AmqpBrokerDecoder.java`, which is high when there are too many broker connections. Increasing the number of connections eventually leads to OOM.
The current memory allocation strategy is that messages smaller than 4K are initialized at 4K per connection and messages larger than 4K are allocated on demand. The previous connection was initialized with a size of 4M.
> bugfix: High Memory usage caused memory overflow.

- amqp-client-auth/pom.xml
- amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/MechanismException.java
- amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/TokenCredentialsProvider.java
- amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/TokenSaslConfig.java
- amqp-client-auth/src/main/java/io/streamnative/rabbitmq/authentication/package-info.java
- amqp-client-auth/src/test/java/io/streamnative/rabbitmq/authentication/TokenSaslConfigTest.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpBrokerService.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpClientDecoder.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConnection.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyConnection.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyHandler.java
- pom.xml
- tests/pom.xml
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTokenAuthenticationTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/authentication/TokenAuthenticationTest.java
Signed-off-by: Zixuan Liu <nodeces@gmail.com>
Fixes #579 
Add token authentication support, this also applies to OAuth2 authentication.
- Add `amqp-client-auth` to provide the JWT authentication
- In the `receiveProtocolHeader` method tells the authentication method name supported to the client 
- In the `receiveConnectionStartOk` providers authenticate the data provided by the client
> feat: add token authentication support

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConnection.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/authentication/AuthenticationProviderBasic.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/authentication/package-info.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTokenAuthenticationTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/authentication/PlainAuthenticationTest.java
Signed-off-by: Zixuan Liu <nodeces@gmail.com>
Add basic authentication support, we depend on https://httpd.apache.org/docs/2.4/programs/htpasswd.html to generate the basic authentication data source.
- Add `io.streamnative.pulsar.handlers.amqp.authentication.AuthenticationProviderBasic` for provide the basic authentication
- This provider reads the `basicAuthConf` from `org.apache.pulsar.broker.ServiceConfiguration` as basic data source, supports both format file and Base64 data, so like: `basicAuthConf=file:///user/dev/.aoppassword` or `basicAuthConf=c3VwZXJVc2VyOm1RUVFJc3l2dktSdFUKc3VwZXJVc2VyMjokYXByMSRmb29iYXJtcSRrdVNabExnT0lUa3NDa1JnbDU3aWUvCg==`
- When using the file format, we can using the password file generated by htpasswd
- When using the Base64 data, we need to encode the the …
> feat: add basic authentication support

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/ProxyHandler.java
Fixes #214 
release the buffer when proxyConnection init
> [fix] release the buf when proxyConnection init

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/PulsarDeduplicationWorkAroundTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
- tests/src/test/resources/log4j2.xml
Master Issue: #572 
If using the basic exclusive consume messages, the AoP will encounter an NPE exception.
```
channel.basicConsume(queueName, false, "", false, true, null,
new DefaultConsumer(channel) {
@Override
public void handleDelivery(String consumerTag,
Envelope envelope,
AMQP.BasicProperties properties,
byte[] body) throws IOException {
long deliveryTag = envelope.getDeliveryTag();
Assert.assertEquals(new String(body), "Hello, world! - " + consumeIndex.getAndIncrement());
channel.basicAck(deliveryTag, false);
}
});
```
```
19:07:56.969 [pulsar-ph-amqp-34-2:io.streamnative.pulsar.handlers.amqp.AmqpConnection@500] DEBUG io.streamnative.pulsar.handlers.amqp.AmqpConnection - send: [CompositeAMQBodyBlock methodBody=[EncodedDeliveryBody underlyingBody: null], …
```
> Fix exclusive consume problem

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConnection.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
Fixes #338 
problem: can not consume large messages (body size > 10*1024)
reason: aop connection doesn't support compression but the method of isCompressionSupported return true
> [fix]consume large messages (body size > 10*1024) failed

- pom.xml
The dependency pulsar-zookeeper-utils is useless and it was removed from the latest Pulsar, remove it.
> Remove pulsar-zookeeper-utils dependency

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpEncodeHandlerTest.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpTopicManagerTest.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/TopicNameTest.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java
- pom.xml
1. Upgrade Pulsar to `2.10.1.4`.
2. Add pulsar bom dependency.
3. Unify using the TestNG framework.
> Add pulsar bom dependency

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpServiceConfiguration.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeService.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeServiceImpl.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueServiceImpl.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/Exchanges.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/Vhosts.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/BaseResources.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/ExchangeBase.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/impl/package-info.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/ExchangeBean.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/ExchangeDeclareParams.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/VhostBean.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/model/package-info.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/admin/package-info.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/common/exception/AoPException.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/utils/ExchangeUtil.java
- tests/src/test/java/com/rabbitmq/client/test/HttpUtil.java
- tests/src/test/java/com/rabbitmq/client/test/JsonUtil.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AdminTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java
Add exchange admin endpoints.
Support list, declare, delete exchange.
*(or)*
*(or)*
*(example:)*
- The rest endpoints: (yes …
> Add exchange admin endpoints

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueServiceImpl.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AdminTest.java
Support delete queue.
Delete all bindings of the queue.
Delete the pulsar topic of the queue.
Remove the queue from the cache.
Add new unit test
> Support delete queue

- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java
- tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
The graceful close operation of the pulsar service may increase test time and cause the test timeout.
Set the broker shutdown timeout to 0.
> [test] Set the broker shutdown timeout to 0

- .github/workflows/pr-qpid-jms-test.yml
- .github/workflows/pr-test.yml
- .github/workflows/release.yml
- README.md
- amqp-client-auth/pom.xml
- amqp-impl/pom.xml
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpPullConsumer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/QueueServiceImpl.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AopProtocolHandlerTestBase.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockManagedLedger.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/mock/MockSubscription.java
- pom.xml
- tests-qpid-jms-client/pom.xml
- tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
- tests/pom.xml
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AdminTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
Bump the Pulsar version to 2.11.
1. Bump the Pulsar version to 2.11, and change some APIs.
2. Use change the workflow JDK version to 17, same with Pulsar.
3. Change the project version to `2.11.0-SNAPSHOT`.
> Bump the Pulsar version to 2.11

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/PulsarServiceLookupHandler.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
Currently, if users want to use the AoP in the Kubernetes environment, they couldn't set the `amqpListeners` and only use the port 5672, because if not specify the `amqpListeners` the proxy lookup result will use this hostname `InetAddress.getLocalHost().getCanonicalHostName()` and it could be resolved by other pods in k8s. Actually, because the AMQP doesn't support lookup operation, the AMQP service address will not be sent to clients, we can use the hostname of the web services directly.
Use the hostname of the web service and AMQP port as the lookup result.
Adjust test.
> Use the web service host name and AMQP port as the lookup result

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpConsumer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpPullConsumer.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
Currently, the async method `consumer.handleFlow(DEFAULT_CONSUMER_PERMIT);` in basic consume command operation doesn't handle in an async way, this may cause NPE problem in the subsequent process.
Start handle flow after subscription adds consumer finished.
- The rest endpoints: (yes / no)
- The admin cli options: (yes / no)
- Anything that affects deployment: (yes / no / don't know)
(If this PR contains doc …
> [bug] Fix consumer subscribe problem for basic consume

- .github/workflows/pr-qpid-jms-test.yml
- .github/workflows/pr-test.yml
- amqp-client-auth/pom.xml
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpExchange.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpQueue.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchange.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpQueue.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentExchange.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentQueue.java
- pom.xml
- tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/qpid/core/AoPBrokerAdmin.java
- tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/qpid/core/QpidJMSTestException.java
- tests-qpid-jms-client/src/test/java/io/streamnative/pulsar/handlers/amqp/qpid/jms_1_1/acknowledge/RecoverTest.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java
Currently, for AoP, messages of the queue topic are only index data, the original data are in the exchange topic, the AmqpConsumer needs to get the original message data from the exchange topic and send it to the client, if messages in the exchange topic are clean up, the AmqpConsumer will not get the data, so queue topics need durable cursors of exchange topic to make sure the original data exists.
This PR will cause the exchange topic can't be cleaned up because the queue only handles part of the exchange data, only these index positions could be acknowledged. I'll create a new PR to fix this problem.
Create durable cursors of the exchange topic for each queue in an async way. …
> Create durable exchange topic cursor for queue

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpExchange.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpChannel.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchange.java
Master Issue: #596
The queue corresponding to the default Exchange cannot consume messages when the broker restarts or the namespace migrates to another broker.
Unload or broker restart can still consume normally.
`Set<AmqpQueue> queues` in Exchange cannot be persisted after the broker has restarted. Queue validation was added to the BasicPublish interface.
- The rest endpoints: (yes / no)
- The admin cli options: (yes / no)
- Anything that affects deployment: (yes / no / don't know)
Need to update docs? …
> bugfix: Default echange consume failed, when broker restart.

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpBrokerService.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandler.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpServiceConfiguration.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/ExchangeContainer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentExchange.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/TopicNameTest.java
Currently, the exchange route process uses the same threads with bk read complete callback.
Use a new executor to route exchange messages.
Add two configurations `amqpExchangeRouteQueueSize` and `amqpExchangeRouteExecutorThreads` to control exchange message routing.
This change is already covered by existing tests.
> Async route exchange messages

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AbstractAmqpExchange.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentExchange.java
Currently, each queue getting the corresponding router will cost a lot of resources, optimize direct and fanout exchange gets router logic, and doesn't need to check every queue.
For direct exchange, use a map to record the routing key map to the bound queue list, when routing messages, get the bound queue list with the binding key and route messages to them.
For fanout exchange, write index messages directly.
*(or)*
*(or)*
*(example:)*
- *Extended …
> Optimize direct and fanout exchange route logic

- .github/CODEOWNERS
Remove @streamnative/platform from CODEOWNERS  since the new PR will invite the CODEOWNERS as the reviewers. But the @streamnative/platform has a lot of engineers. Everyone under the @streamnative/platform will receive the Github notifications.
> Remove @streamnative/platform from CODEOWNERS

- amqp-impl/pom.xml
- pom.xml
- tests-qpid-jms-client/pom.xml
- tests/pom.xml
Currently, the project dependencies are confusing, and the release NAR package is too big(bigger than 100MB).
Thanks for the suggestion from the AoP community guys(Geeker, tangᴗg), after this change, the release NAR package can reduce to 6.5MB.
1. Use the tag `dependencyManagement` to define all used dependencies.
2. Add provide scope for dependency `pulsar-broker`, this is why the release package is too big.
3. Remove duplicate and useless dependencies.
4. Move common dependencies to the root POM file.
> [fix] Improve dependencies

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/MessageFetchContext.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/utils/MessageConvertUtils.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/MessageConvertTest.java
Support keep amqp message header's original type.
In previous processing, all header field type will be formet to `String`.
Use hex to encode and decode all headers, so that client can get the original field and field type such as `FieldArray`.
Check the box below and label this PR (if you have committer privilege).
Need to update docs?
> Fix - Support keep amqp message header's original type.

- .github/workflows/pr-qpid-jms-test.yml
Currently, the jms1_1 test is not stable, and we can't provide a guarantee that AoP supports jms1_1, I think we can ignore the jms1_1 test workflow first.
After verifying the jms1_1 tests, we can reopen this workflow.
Ignore the jms1_1 test workflow.
> [test] Ignore the jms1_1 test workflow

- amqp-impl/pom.xml
Currently, the "com.rabbitmq:amqp-client" dependency is from bookkeeper-stats, we should dependent it directly.
```
+- io.streamnative:managed-ledger:jar:3.0.0.1-SNAPSHOT:provided
|  +- org.apache.bookkeeper.stats:prometheus-metrics-provider:jar:4.15.3:provided
|  |  +- org.apache.bookkeeper.stats:bookkeeper-stats-api:jar:4.15.3:provided
|  |  \- io.prometheus:simpleclient_servlet:jar:0.16.0:provided
|  |     +- io.prometheus:simpleclient_common:jar:0.16.0:provided
|  |     \- io.prometheus:simpleclient_servlet_common:jar:0.16.0:provided
|  +- org.apache.bookkeeper.stats:codahale-metrics-provider:jar:4.15.3:provided
|  |  +- io.dropwizard.metrics:metrics-jmx:jar:4.1.12.1:provided
|  |  +- io.dropwizard.metrics:metrics-jvm:jar:4.1.12.1:provided
|  |  \- …
```
> Add RabbitMQ amqp-client dependency for test

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpPulsarServerCnx.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/proxy/PulsarServiceLookupHandler.java
- pom.xml
Compatible ServerCnx code, it be introduce from https://github.com/apache/pulsar/pull/21682
> [fix] Bump pulsar version to 3.2.0-SNAPSHOT & Compatible ServerCnx code

- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/functional/ExchangeDeclareTest.java
Improve the declare exchange test.
> [fix][test] Improve the declare exchange test

- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpExchangeReplicator.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/AmqpPulsarConsumer.java
- amqp-impl/src/main/java/io/streamnative/pulsar/handlers/amqp/impl/PersistentExchange.java
- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpProtocolHandlerTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/AmqpTestBase.java
- tests/src/test/java/io/streamnative/pulsar/handlers/amqp/rabbitmq/RabbitMQMessagingTest.java
The [PR](https://github.com/apache/pulsar/pull/18245) introduced the InflightReadsLimiter, the exchange replicator will read data and route index data to the queue topic, but it doesn't release the EntryImpl object, this will cause the broker in-flight read cache limiter to be exhausted.
Release `EntryImpl` object while reading the exchange topic.
Use topic dispatch limiter to control read batch size.
Add test to verify the in-flight read cache can't be exhausted.
> [fix] Release `EntryImpl` while reading exchange topic

- .github/workflows/pr-test.yml
- amqp-client-auth/pom.xml
- amqp-impl/pom.xml
- pom.xml
- scripts/build.sh
- tests-qpid-jms-client/pom.xml
- tests/pom.xml
https://github.com/streamnative/snip/pull/82
*(or)*
*(or)*
*(example:)*
- The rest …
> Use SN bom

- pom.xml
We should use `${sn.bom.version}` for the sn-bom version. Otherwise it would block the release.
> Fix SN bom version

- .github/workflows/pr-test.yml
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
> Upgrade artifact github action version

- pom.xml
We will use github private maven repository widely in the future including streamnative/pulsar's.
It is convenient to use wildcard repository url to match all the maven packages of SN org.
> Use Github package wildcard repository url

- amqp-impl/src/test/java/io/streamnative/pulsar/handlers/amqp/test/AmqpProtocolTestBase.java
Fix configuration potential NPE in test.
Use a spy configuration object instead of a mock configuration object.
> [fix][test] Fix configuration potential NPE in test
